### ISSUE TITLE
Slippery values in Category

### ISSUE THREAD

**Issue by babenek** [Samsung/CredData#71]
Sometime various data processing tools require different approach to escaping the category:

``Authentication Key & Token`` - sometime & requires to escape it in data processing
``"Seed, Salt, Nonce"`` - requires quotes escaping in csv

### Proposition 1:
Rename
Authentication Key & Token -> Authentication Credential
"Seed, Salt, Nonce" - > Cryptographic Primitives

### Proposition 2:
Use rule names instead the category
Other issue - multiple rules for one value e.g. ``Auth_key_secret = blablabal`` - Key Auth and Secret rules

**Comment by csh519** [comment]
Thank you for share the issue and its solution.

I think proposal 1 would be good.
